// Package wrapperbinding defines the host-neutral closure embedded in one
// generated Atsura wrapper.
package wrapperbinding

import (
	"bytes"
	"crypto/sha256"
	"errors"
	"fmt"
	"path/filepath"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/tasuku43/atsura/internal/domain/sourceprocess"
	"github.com/tasuku43/atsura/internal/domain/tailoringbundle"
)

const (
	// ContractVersion adds compiled ordinary tailored help to the host-neutral
	// wrapper material while retaining the same runtime invocation closure.
	ContractVersion = 2

	MaxBundleLocatorBytes  = 4096
	MaxCommandNameBytes    = 255
	MaxRuntimePathBytes    = 4096
	MaxRenderedSourceBytes = 64 * 1024
)

var (
	ErrInvalidBinding        = errors.New("invalid wrapper binding")
	ErrInvalidRenderedSource = errors.New("invalid rendered wrapper source")
)

// RuntimeIdentity binds a generated wrapper to the exact Atsura executable
// that rendered it. It is deliberately distinct from the source executable
// identity already carried by the bundle.
type RuntimeIdentity struct {
	ResolvedPath string `json:"resolved_path"`
	SHA256       string `json:"sha256"`
	Size         int64  `json:"size"`
}

// Binding contains only product-owned facts needed to close one generated
// wrapper over an exact bundle and Atsura runtime.
type Binding struct {
	ContractVersion int             `json:"contract_version"`
	BundleLocator   string          `json:"bundle_locator"`
	BundleDigest    string          `json:"bundle_digest"`
	CommandName     string          `json:"command_name"`
	Help            CompiledHelp    `json:"help"`
	Runtime         RuntimeIdentity `json:"runtime"`
}

// RuntimeInvocation is the complete binding accepted by the host-neutral
// wrapper runtime. The ordinary command spelling is intentionally absent: the
// runtime derives it from the one strictly loaded bundle instead of accepting
// another caller-controlled representation of the same fact.
type RuntimeInvocation struct {
	ContractVersion int             `json:"contract_version"`
	BundleLocator   string          `json:"bundle_locator"`
	BundleDigest    string          `json:"bundle_digest"`
	Runtime         RuntimeIdentity `json:"runtime"`
}

// RenderedMaterial is the bounded deterministic product emitted for one
// wrapper binding. Its digest is review evidence over Source; it is not
// attestation after a caller activates or changes those bytes.
type RenderedMaterial struct {
	Source []byte
	SHA256 string
}

// NewRenderedMaterial binds one exact bounded wrapper source to its lowercase
// SHA-256 digest and detaches it from the renderer's working buffer.
func NewRenderedMaterial(source []byte) (RenderedMaterial, error) {
	material := RenderedMaterial{Source: append([]byte(nil), source...)}
	digest := sha256.Sum256(material.Source)
	material.SHA256 = fmt.Sprintf("%x", digest)
	if err := material.Validate(); err != nil {
		return RenderedMaterial{}, err
	}
	return material, nil
}

// Validate rejects empty, unbounded, non-UTF-8, NUL-bearing, or digest-drifted
// generated material. Shell grammar remains the fixed renderer's contract.
func (m RenderedMaterial) Validate() error {
	if len(m.Source) == 0 || len(m.Source) > MaxRenderedSourceBytes || !utf8.Valid(m.Source) || bytes.IndexByte(m.Source, 0) >= 0 {
		return fmt.Errorf("%w: source must be non-empty bounded NUL-free UTF-8", ErrInvalidRenderedSource)
	}
	if !validDigest(m.SHA256) {
		return fmt.Errorf("%w: digest must contain 64 lowercase hex characters", ErrInvalidRenderedSource)
	}
	digest := sha256.Sum256(m.Source)
	if m.SHA256 != fmt.Sprintf("%x", digest) {
		return fmt.Errorf("%w: digest does not match source bytes", ErrInvalidRenderedSource)
	}
	return nil
}

// Clone detaches the generated bytes before they cross another application
// or presentation boundary.
func (m RenderedMaterial) Clone() RenderedMaterial {
	return RenderedMaterial{Source: append([]byte(nil), m.Source...), SHA256: m.SHA256}
}

// New derives the ordinary command spelling verbatim from the bundle. A
// bundle locator is syntax-only evidence here; the application loader remains
// responsible for proving that it names a stable regular file.
func New(bundleLocator, bundleDigest string, bundle tailoringbundle.Bundle, runtime sourceprocess.Identity) (Binding, error) {
	if err := bundle.Validate(); err != nil {
		return Binding{}, invalid("bundle: %v", err)
	}
	wantedDigest, err := bundle.Digest()
	if err != nil || wantedDigest != bundleDigest {
		return Binding{}, invalid("bundle digest does not match the supplied bundle")
	}
	help, err := CompileHelp(bundle)
	if err != nil {
		return Binding{}, invalid("compiled help: %v", err)
	}
	binding := Binding{
		ContractVersion: ContractVersion,
		BundleLocator:   bundleLocator,
		BundleDigest:    bundleDigest,
		CommandName:     bundle.Catalog.Source.RequestedExecutable,
		Help:            help,
		Runtime: RuntimeIdentity{
			ResolvedPath: runtime.ResolvedPath,
			SHA256:       runtime.SHA256,
			Size:         runtime.Size,
		},
	}
	if err := binding.ValidateAgainstBundle(bundle); err != nil {
		return Binding{}, err
	}
	return binding, nil
}

// RuntimeInvocation returns the exact subset embedded as wrapper-run flags.
// It never copies or derives CommandName into that invocation boundary.
func (b Binding) RuntimeInvocation() RuntimeInvocation {
	return RuntimeInvocation{
		ContractVersion: b.ContractVersion,
		BundleLocator:   b.BundleLocator,
		BundleDigest:    b.BundleDigest,
		Runtime:         b.Runtime,
	}
}

// Clone detaches every generated-help slice before the binding crosses an
// application or rendering boundary.
func (b Binding) Clone() Binding {
	result := b
	result.Help = b.Help.Clone()
	return result
}

// Equal compares the complete semantic binding, including compiled help,
// without relying on Go comparability for slice-bearing domain values.
func (b Binding) Equal(other Binding) bool {
	return b.ContractVersion == other.ContractVersion &&
		b.BundleLocator == other.BundleLocator &&
		b.BundleDigest == other.BundleDigest &&
		b.CommandName == other.CommandName &&
		b.Runtime == other.Runtime &&
		b.Help.Equal(other.Help)
}

// Validate rejects incomplete, ambiguous, unbounded, or structurally unsafe
// wrapper facts without consulting the filesystem.
func (b Binding) Validate() error {
	if err := b.RuntimeInvocation().Validate(); err != nil {
		return err
	}
	if err := ValidateCommandName(b.CommandName); err != nil {
		return invalid("command name: %v", err)
	}
	if err := b.Help.Validate(); err != nil {
		return invalid("compiled help: %v", err)
	}
	return nil
}

// Validate rejects incomplete, ambiguous, unbounded, or structurally unsafe
// wrapper-run flags without consulting the filesystem or deriving a command
// name from a path.
func (i RuntimeInvocation) Validate() error {
	if i.ContractVersion != ContractVersion {
		return invalid("contract_version must be %d", ContractVersion)
	}
	if err := ValidateBundleLocator(i.BundleLocator); err != nil {
		return invalid("bundle locator: %v", err)
	}
	if !validDigest(i.BundleDigest) {
		return invalid("bundle digest must contain 64 lowercase hex characters")
	}
	if err := i.Runtime.Validate(); err != nil {
		return invalid("runtime identity: %v", err)
	}
	return nil
}

// ValidateBundleLocator applies the exact syntax required before an
// application service passes a path to the strict bundle loader.
func ValidateBundleLocator(value string) error {
	return validateAbsolutePath(value, MaxBundleLocatorBytes)
}

// ValidateAgainstBundle proves the digest and ordinary command spelling
// against one strictly validated bundle. The comparison is exact and never
// derives a command name from the bundle locator or resolved source path.
func (b Binding) ValidateAgainstBundle(bundle tailoringbundle.Bundle) error {
	if err := b.Validate(); err != nil {
		return err
	}
	if err := bundle.Validate(); err != nil {
		return invalid("bundle: %v", err)
	}
	wantedDigest, err := bundle.Digest()
	if err != nil || b.BundleDigest != wantedDigest {
		return invalid("bundle digest does not match the supplied bundle")
	}
	if b.CommandName != bundle.Catalog.Source.RequestedExecutable {
		return invalid("command name does not match bundle requested_executable")
	}
	wantedHelp, err := CompileHelp(bundle)
	if err != nil || !b.Help.Equal(wantedHelp) {
		return invalid("compiled help does not match the supplied bundle")
	}
	return nil
}

// Validate rejects a runtime identity that is not exact, absolute, bounded,
// and safe to place in generated source.
func (i RuntimeIdentity) Validate() error {
	if err := validateAbsolutePath(i.ResolvedPath, MaxRuntimePathBytes); err != nil {
		return fmt.Errorf("resolved path: %v", err)
	}
	identity := sourceprocess.Identity{ResolvedPath: i.ResolvedPath, SHA256: i.SHA256, Size: i.Size}
	if err := identity.Validate(); err != nil {
		return err
	}
	return nil
}

// SourceProcessIdentity returns the shared exact-executable identity shape.
func (i RuntimeIdentity) SourceProcessIdentity() sourceprocess.Identity {
	return sourceprocess.Identity{ResolvedPath: i.ResolvedPath, SHA256: i.SHA256, Size: i.Size}
}

// ValidateCommandName enforces the portable POSIX Name grammar and excludes
// reserved words, fixed utilities, and maintained-shell function conflicts.
// Invalid spellings are rejected rather than normalized from a source path.
func ValidateCommandName(value string) error {
	if value == "" || len(value) > MaxCommandNameBytes || !utf8.ValidString(value) {
		return fmt.Errorf("must be a non-empty bounded portable POSIX Name")
	}
	for index, r := range value {
		if (index == 0 && !asciiNameStart(r)) || (index > 0 && !asciiNameContinue(r)) {
			return fmt.Errorf("must match [A-Za-z_][A-Za-z0-9_]*")
		}
	}
	if _, reserved := reservedWords[value]; reserved {
		return fmt.Errorf("must not be a POSIX shell reserved word")
	}
	if _, special := specialBuiltins[value]; special {
		return fmt.Errorf("must not be a POSIX shell special built-in")
	}
	if _, fixed := forbiddenWrapperFunctionNames[value]; fixed {
		return fmt.Errorf("must not be a generated-wrapper function name")
	}
	return nil
}

func validateAbsolutePath(value string, limit int) error {
	if value == "" || len(value) > limit || !utf8.ValidString(value) {
		return fmt.Errorf("must be non-empty bounded UTF-8")
	}
	if strings.IndexFunc(value, func(r rune) bool {
		return unicode.IsControl(r) || unicode.Is(unicode.Cf, r) || r == '\u2028' || r == '\u2029'
	}) >= 0 {
		return fmt.Errorf("contains unsupported structural text")
	}
	if !filepath.IsAbs(value) || filepath.Clean(value) != value {
		return fmt.Errorf("must be absolute and clean")
	}
	return nil
}

func validDigest(value string) bool {
	if len(value) != 64 {
		return false
	}
	for _, r := range value {
		if !((r >= '0' && r <= '9') || (r >= 'a' && r <= 'f')) {
			return false
		}
	}
	return true
}

func asciiNameStart(r rune) bool {
	return (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') || r == '_'
}

func asciiNameContinue(r rune) bool {
	return asciiNameStart(r) || (r >= '0' && r <= '9')
}

var reservedWords = map[string]struct{}{
	"case":  {},
	"do":    {},
	"done":  {},
	"elif":  {},
	"else":  {},
	"esac":  {},
	"fi":    {},
	"for":   {},
	"if":    {},
	"in":    {},
	"then":  {},
	"until": {},
	"while": {},
}

var specialBuiltins = map[string]struct{}{
	"break":    {},
	"continue": {},
	"eval":     {},
	"exec":     {},
	"exit":     {},
	"export":   {},
	"readonly": {},
	"return":   {},
	"set":      {},
	"shift":    {},
	"times":    {},
	"trap":     {},
	"unset":    {},
}

// Generated material must parse as a function in each maintained POSIX-shell
// family. These implementation-reserved words are not all POSIX reserved
// words, and `command` is also used by the fixed help branch.
var forbiddenWrapperFunctionNames = map[string]struct{}{
	"command":  {},
	"coproc":   {},
	"function": {},
	"local":    {},
	"select":   {},
	"time":     {},
	"unalias":  {},
}

func invalid(format string, args ...any) error {
	return fmt.Errorf("%w: %s", ErrInvalidBinding, fmt.Sprintf(format, args...))
}
